"""Delta D3 — Independent Pipeline Reproducibility.

Regenerates the certification reports for all three verticals from
scratch (fresh subprocess, no cached artifacts) and compares them,
field-for-field, against the frozen reference reports committed to the
repository. Also runs benchmark.selftest. Exits nonzero on any mismatch
(Failure Criteria F1-F4) so a CI job fails loudly, not silently.

Frozen reference reports (canonical, committed, never regenerated by
this script - this script only READS them for comparison):
  - research/G3_cert_independence/report_20260703-124811.json      (edge_ai)
  - research/G3_cert_independence/report_csp_20260703-161208.json  (constraint_csp)
  - research/D2_lp_vertical/report_20260703-172506.json            (optimization_lp)

    python3 -m research.D3_independent_reproduction.reproduce
"""

from __future__ import annotations

import datetime
import hashlib
import json
import os
import platform
import subprocess
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
HERE = os.path.dirname(__file__)

REFERENCES = {
    "edge_ai (Gamma+1)": {
        "frozen": "research/G3_cert_independence/report_20260703-124811.json",
        "module": "research.G3_cert_independence.run",
        "glob_prefix": "report_",
        "dir": "research/G3_cert_independence",
    },
    "constraint_csp (Gamma+2)": {
        "frozen": "research/G3_cert_independence/report_csp_20260703-161208.json",
        "module": "research.G3_cert_independence.run_csp",
        "glob_prefix": "report_csp_",
        "dir": "research/G3_cert_independence",
    },
    "optimization_lp (D2)": {
        "frozen": "research/D2_lp_vertical/report_20260703-172506.json",
        "module": "research.D2_lp_vertical.run",
        "glob_prefix": "report_",
        "dir": "research/D2_lp_vertical",
    },
}


def _sha256(obj) -> str:
    return hashlib.sha256(json.dumps(obj, sort_keys=True).encode()).hexdigest()


def _latest_report(dirpath: str, prefix: str, before: set[str]) -> str:
    """The report file this run just wrote (present now, absent before)."""
    now = {f for f in os.listdir(dirpath) if f.startswith(prefix) and f.endswith(".json")}
    new = now - before
    if len(new) != 1:
        raise RuntimeError(f"expected exactly 1 new report in {dirpath}, found {new}")
    return os.path.join(dirpath, new.pop())


def run_selftest(log: list[str]) -> bool:
    log.append("=== benchmark.selftest ===")
    r = subprocess.run([sys.executable, "-m", "benchmark.selftest"],
                       cwd=REPO_ROOT, capture_output=True, text=True)
    log.append(r.stdout.strip())
    if r.returncode != 0:
        log.append(r.stderr.strip())
    log.append(f"exit code: {r.returncode}")
    return r.returncode == 0


def run_experiment(name: str, cfg: dict, log: list[str]) -> dict:
    dirpath = os.path.join(REPO_ROOT, cfg["dir"])
    before = {f for f in os.listdir(dirpath) if f.startswith(cfg["glob_prefix"]) and f.endswith(".json")}
    log.append(f"=== {name}: {cfg['module']} ===")
    r = subprocess.run([sys.executable, "-m", cfg["module"]], cwd=REPO_ROOT,
                       capture_output=True, text=True)
    log.append(f"exit code: {r.returncode}")
    if r.returncode != 0:
        log.append(r.stderr.strip())
        return {"name": name, "ran": False, "match": False, "reason": "nonzero exit"}

    fresh_path = _latest_report(dirpath, cfg["glob_prefix"], before)
    with open(fresh_path) as fh:
        fresh = json.load(fh)
    with open(os.path.join(REPO_ROOT, cfg["frozen"])) as fh:
        frozen = json.load(fh)

    summary_match = fresh["summary"] == frozen["summary"]
    rows_match = fresh["rows"] == frozen["rows"]
    fresh_hash = _sha256(fresh)
    frozen_hash = _sha256(frozen)

    log.append(f"fresh report:  {os.path.relpath(fresh_path, REPO_ROOT)}  sha256={fresh_hash}")
    log.append(f"frozen report: {cfg['frozen']}  sha256={frozen_hash}")
    log.append(f"summary identical: {summary_match} | rows identical: {rows_match}")

    diff = None
    if not (summary_match and rows_match):
        diff = {"summary_diff": {} if summary_match else
               {k: (frozen["summary"].get(k), fresh["summary"].get(k))
                for k in set(frozen["summary"]) | set(fresh["summary"])
                if frozen["summary"].get(k) != fresh["summary"].get(k)}}

    os.remove(fresh_path)  # this run's report is a reproduction check, not new evidence
    return {"name": name, "ran": True, "match": summary_match and rows_match,
           "fresh_hash": fresh_hash, "frozen_hash": frozen_hash,
           "content_identical_despite_hash": (summary_match and rows_match and fresh_hash != frozen_hash),
           "diff": diff}


def environment_manifest() -> dict:
    git_sha = subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPO_ROOT,
                             capture_output=True, text=True).stdout.strip()
    git_dirty = subprocess.run(["git", "status", "--porcelain"], cwd=REPO_ROOT,
                               capture_output=True, text=True).stdout.strip()
    return {
        "python_version": sys.version,
        "platform": platform.platform(),
        "machine": platform.machine(),
        "git_commit": git_sha,
        "git_working_tree_clean": git_dirty == "",
        "third_party_dependencies": "none - certification path is stdlib-only (verified by import audit)",
        "timestamp_utc": datetime.datetime.utcnow().isoformat() + "Z",
    }


def main() -> int:
    log: list[str] = []
    env = environment_manifest()
    log.append("=== environment manifest ===")
    log.append(json.dumps(env, indent=2))

    selftest_ok = run_selftest(log)

    results = []
    if selftest_ok:
        for name, cfg in REFERENCES.items():
            results.append(run_experiment(name, cfg, log))

    all_match = selftest_ok and all(r["match"] for r in results)
    report = {
        "environment": env,
        "selftest_passed": selftest_ok,
        "experiments": results,
        "all_deterministic_outputs_reproduced": all_match,
        "decision": "KEEP" if all_match else "INVALIDATED",
    }

    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    with open(os.path.join(HERE, f"reproduction_log_{stamp}.txt"), "w") as fh:
        fh.write("\n".join(log) + "\n")
    with open(os.path.join(HERE, f"reproduction_report_{stamp}.json"), "w") as fh:
        json.dump(report, fh, indent=2)

    print(json.dumps(report, indent=2))
    return 0 if all_match else 1


if __name__ == "__main__":
    sys.exit(main())
